# -*- coding: utf-8 -*-
"""HTML Quick Styler

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HUT0KOWKRJHmK4bQIiUy3_VahD1snMkT
"""

# 🔧 Colab setup: run this once
!pip -q install "gradio==5.50.0" "websockets>=15,<17" "uvicorn==0.41.0" \
               "huggingface_hub>=0.21.4" "transformers>=4.44.0" \
               "jinja2>=3.1.3" "markdown2>=2.4.10" "requests>=2.32.4,<3"

# =========================
# HTML Quick‑Styler (fixed)
# - Correct <a> tags in header/hero
# - Proper <link rel="stylesheet"> for external CSS
# - Safer callback (try/except with friendly error)
# =========================

import os, re, json, textwrap, tempfile, zipfile
from dataclasses import dataclass
from datetime import datetime
from typing import Dict, List, Tuple, Optional
from urllib.parse import quote

import gradio as gr
from jinja2 import Template
from huggingface_hub import InferenceClient

# ---------- Color Palettes ----------
@dataclass
class Palette:
    name: str
    colors: Dict[str, str]

class ColorPaletteGenerator:
    def __init__(self):
        self.palettes: Dict[str, Palette] = {
            "modern":   Palette("modern",   dict(primary="#7C3AED", secondary="#22D3EE", accent="#F59E0B", bg="#0B1020", surface="#111827", text="#E5E7EB", text_muted="#9CA3AF", border="#1F2937")),
            "vibrant":  Palette("vibrant",  dict(primary="#EF4444", secondary="#10B981", accent="#3B82F6", bg="#0D0D0D", surface="#171717", text="#FAFAFA", text_muted="#A3A3A3", border="#262626")),
            "ocean":    Palette("ocean",    dict(primary="#0EA5E9", secondary="#22D3EE", accent="#14B8A6", bg="#05121F", surface="#0B2436", text="#E6F6FF", text_muted="#9CC6DD", border="#10344C")),
            "forest":   Palette("forest",   dict(primary="#16A34A", secondary="#22C55E", accent="#84CC16", bg="#0D1411", surface="#0F1E17", text="#E6FDF0", text_muted="#A8DABF", border="#1B3A2B")),
            "sunset":   Palette("sunset",   dict(primary="#F97316", secondary="#EF4444", accent="#F59E0B", bg="#140B0B", surface="#1C1010", text="#FFF1E6", text_muted="#F5CBA7", border="#2C1A14")),
            "luxury":   Palette("luxury",   dict(primary="#C5A46D", secondary="#8B7355", accent="#E6C988", bg="#0A0A0A", surface="#121212", text="#F4EDE4", text_muted="#C9BBAA", border="#26211A")),
            "creative": Palette("creative", dict(primary="#A855F7", secondary="#06B6D4", accent="#F43F5E", bg="#0A0E1A", surface="#11152A", text="#EDE9FE", text_muted="#BDB4FE", border="#1B2140")),
            "minimal":  Palette("minimal",  dict(primary="#6B7280", secondary="#94A3B8", accent="#A3A3A3", bg="#0B0B0B", surface="#151515", text="#FFFFFF", text_muted="#CFCFCF", border="#2A2A2A")),
        }
    def names(self) -> List[str]:
        return list(self.palettes.keys())
    def get(self, key: str) -> Palette:
        return self.palettes.get(key, self.palettes["modern"])
    def palette_cards_html(self) -> str:
        tpl = Template("""
        <style>
            .pal-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px}
            .pal-card{border:1px solid var(--border,#222);border-radius:12px;overflow:hidden;background:#0f1221}
            .pal-head{padding:10px 12px;background:linear-gradient(90deg, var(--p), var(--s));color:#fff;font-weight:600}
            .sw{display:flex;gap:6px;flex-wrap:wrap;padding:10px}
            .chip{flex:1 0 30%;min-width:100px;height:34px;border-radius:8px;display:flex;align-items:center;justify-content:center;font:12px/1.1 ui-monospace,Consolas,monospace;color:#000;font-weight:700}
            .chip span{background:rgba(255,255,255,.8);padding:1px 6px;border-radius:6px}
            .code{padding:10px;font:12px/1.5 ui-monospace,Consolas,monospace;color:#ddd}
        </style>
        <div class="pal-grid">
        {% for pal in palettes %}
          <div class="pal-card" style="--p:{{pal.colors.primary}};--s:{{pal.colors.secondary}};--border:{{pal.colors.border}}">
            <div class="pal-head">{{pal.name|title}}</div>
            <div class="sw">
              {% for k,v in pal.colors.items() %}
                <div class="chip" style="background:{{v}}"><span>{{k}}: {{v}}</span></div>
              {% endfor %}
            </div>
            <div class="code"><strong>CSS vars:</strong>
<pre>:root { --color-primary: {{pal.colors.primary}}; --color-secondary: {{pal.colors.secondary}}; --color-accent: {{pal.colors.accent}}; --color-bg: {{pal.colors.bg}}; --color-surface: {{pal.colors.surface}}; --color-text: {{pal.colors.text}}; --color-text-muted: {{pal.colors.text_muted}}; --color-border: {{pal.colors.border}}; }</pre>
            </div>
          </div>
        {% endfor %}
        </div>""")
        return tpl.render(palettes=list(self.palettes.values()))

# ---------- Section detection ----------
SECTION_KEYWORDS = {
    "hero": ["hero", "banner", "headline", "welcome", "cta", "call to action"],
    "features": ["feature", "benefit", "capability", "why", "value"],
    "about": ["about", "bio", "story", "mission", "vision"],
    "portfolio": ["portfolio", "work", "projects", "gallery"],
    "testimonials": ["testimonial", "reviews", "feedback", "social proof"],
    "pricing": ["pricing", "plan", "plans", "subscription", "package"],
    "contact": ["contact", "reach", "email", "form", "inquiry"],
    "footer": ["footer", "copyright", "policy", "links"],
}
def detect_sections(description: str) -> List[str]:
    t = (description or "").lower()
    found = [sec for sec, kws in SECTION_KEYWORDS.items() if any(k in t for k in kws)]
    if not found:
        found = ["hero", "features", "about", "contact", "footer"]
    if "footer" not in found:
        found.append("footer")
    return found

# ---------- Optional Granite helper ----------
class GraniteHelper:
    def __init__(self, token: Optional[str], model_id: str = "ibm-granite/granite-3.3-2b-instruct"):
        self.token = token.strip() if token else None
        self.model_id = model_id
        self.client = InferenceClient(token=self.token) if self.token else None
    def enabled(self) -> bool:
        return self.client is not None
    def infer(self, prompt: str, max_new_tokens: int = 160, temperature: float = 0.7) -> str:
        if not self.enabled():
            return ""
        try:
            out = self.client.text_generation(
                model=self.model_id, prompt=prompt,
                max_new_tokens=max_new_tokens, temperature=temperature,
                repetition_penalty=1.05, stream=False,
            )
            return (out or "").strip()
        except Exception as e:
            print("Granite error:", e)  # keep running
            return ""
    def hero(self, title: str) -> Tuple[str, str]:
        default_head = title or "Welcome"
        default_tag = "Build something remarkable."
        if not self.enabled():
            return default_head, default_tag
        txt = self.infer(
            f'Create JSON: {{"h1":"(<=6 words)", "tagline":"(<=14 words)"}} '
            f'for landing page titled "{title}".'
        )
        try:
            data = json.loads(re.search(r"\{.*\}", txt, re.S).group(0))
            return data.get("h1", default_head), data.get("tagline", default_tag)
        except Exception:
            return default_head, default_tag
    def bullets(self, topic: str, n: int = 3) -> List[str]:
        if not self.enabled():
            return ["Fast to start", "Beautifully styled", "Mobile‑ready"][:n]
        txt = self.infer(f"List {n} short feature bullets (<=8 words) for {topic}. Return JSON array.")
        try:
            arr = json.loads(re.search(r"\[.*\]", txt, re.S).group(0))
            return [str(x) for x in arr][:n]
        except Exception:
            return ["Fast to start", "Beautifully styled", "Mobile‑ready"][:n]
    def short_para(self, topic: str, words: int = 40) -> str:
        if not self.enabled():
            return "We craft thoughtful experiences with a focus on clarity, speed, and delightful design."
        txt = self.infer(f"Write a {words}-word paragraph about: {topic}.", max_new_tokens=words*2, temperature=0.8)
        return txt or "We craft thoughtful experiences with a focus on clarity, speed, and delightful design."

# ---------- CSS ----------
def generate_css(pal: Palette) -> str:
    return textwrap.dedent(f"""
    :root {{
      --color-primary: {pal.colors['primary']};
      --color-secondary: {pal.colors['secondary']};
      --color-accent: {pal.colors['accent']};
      --color-bg: {pal.colors['bg']};
      --color-surface: {pal.colors['surface']};
      --color-text: {pal.colors['text']};
      --color-text-muted: {pal.colors['text_muted']};
      --color-border: {pal.colors['border']};
      --maxw: 1200px;
      --radius: 14px;
      --shadow: 0 10px 30px rgba(0,0,0,.35);
    }}
    *,*:before,*:after{{box-sizing:border-box}}
    html,body{{margin:0;padding:0;background:var(--color-bg);color:var(--color-text);font:16px/1.6 system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,sans-serif}}
    a{{color:var(--color-secondary);text-decoration:none}}
    img{{max-width:100%;display:block}}
    header.sticky{{position:sticky;top:0;backdrop-filter:blur(8px);background:color-mix(in oklab, var(--color-bg), transparent 30%);border-bottom:1px solid var(--color-border);z-index:50}}
    .nav{{max-width:var(--maxw);margin:0 auto;display:flex;align-items:center;justify-content:space-between;padding:12px 20px}}
    .brand{{font-weight:800;letter-spacing:.3px;color:var(--color-text)}}
    .cta{{padding:10px 16px;border-radius:10px;background:linear-gradient(135deg,var(--color-primary),var(--color-secondary));color:#fff;box-shadow:var(--shadow)}}
    .btn{{padding:10px 16px;border-radius:10px;background:var(--color-secondary);color:#000;border:1px solid var(--color-border)}}
    .hero{{max-width:var(--maxw);margin:48px auto;padding:0 20px;display:grid;gap:18px}}
    .hero h1{{font-size:clamp(2rem,5vw,3.2rem);line-height:1.15;margin:0}}
    .hero p{{color:var(--color-text-muted);margin:0}}
    .hero .cta-row{{display:flex;gap:12px;margin-top:12px;flex-wrap:wrap}}
    .section{{max-width:var(--maxw);margin:54px auto;padding:0 20px}}
    .grid-3{{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}}
    .card{{background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius);padding:18px;box-shadow:var(--shadow)}}
    .muted{{color:var(--color-text-muted)}}
    .features .icon{{width:40px;height:40px;border-radius:10px;background:linear-gradient(135deg,var(--color-secondary),var(--color-accent));display:flex;align-items:center;justify-content:center;color:#000;font-weight:800}}
    .pricing .plan{{border:1px solid var(--color-border);border-radius:var(--radius);padding:22px;background:var(--color-surface);box-shadow:var(--shadow)}}
    .pricing .price{{font-size:28px;font-weight:800}}
    .gallery{{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}}
    .gallery .tile{{aspect-ratio:4/3;background:linear-gradient(135deg,var(--color-secondary),var(--color-primary));border-radius:10px;opacity:.9}}
    form .row{{display:grid;grid-template-columns:1fr 1fr;gap:12px}}
    input,textarea{{width:100%;padding:12px;border-radius:10px;border:1px solid var(--color-border);background:#0a0a0a;color:var(--color-text)}}
    button.btn{{padding:12px 16px;border-radius:10px;background:var(--color-primary);color:#fff;border:none;cursor:pointer;box-shadow:var(--shadow)}}
    footer{{border-top:1px solid var(--color-border);padding:24px 20px;color:var(--color-text-muted)}}
    @media (max-width: 900px){{ .grid-3{{grid-template-columns:1fr}} form .row{{grid-template-columns:1fr}} }}
    """)

# ---------- HTML sections (fixed anchors) ----------
def hero_section(title: str, tagline: str) -> str:
    return f"""
    <section class="hero">
      <h1>{title}</h1>
      <p>{tagline}</p>
      <div class="cta-row">
        <a class="cta" href="#contact">Get Started</a>
        <a class="btn" href="#features">See Features</a>
      </div>
    </section>"""

def features_section(bullets: List[str]) -> str:
    items = "".join(f"""
      <div class="card">
        <div class="icon">★</div>
        <h3>{b}</h3>
        <p class="muted">Clear value explained in one short sentence.</p>
      </div>""" for b in bullets)
    return f'<section id="features" class="section features"><div class="grid-3">{items}</div></section>'

def about_section(text: str) -> str:
    return f'<section id="about" class="section"><div class="card"><h2>About</h2><p class="muted">{text}</p></div></section>'

def portfolio_section(n: int = 6) -> str:
    tiles = ''.join('<div class="tile"></div>' for _ in range(n))
    return f'<section id="portfolio" class="section"><h2>Portfolio</h2><div class="gallery">{tiles}</div></section>'

def testimonials_section() -> str:
    sample = [("“Transformed our workflow!”", "— Alex P."),
              ("“Clean, fast, and delightful.”", "— Priya K."),
              ("“Exactly what we needed.”", "— Daniel R.")]
    cards = "".join(f'<div class="card"><p>{q}</p><p class="muted">{a}</p></div>' for q,a in sample)
    return f'<section id="testimonials" class="section"><h2>Testimonials</h2><div class="grid-3">{cards}</div></section>'

def pricing_section() -> str:
    plans = [
        ("Starter", "$0", ["1 project", "Basic support", "Community"]),
        ("Pro", "$19", ["Unlimited projects", "Priority support", "Advanced features"]),
        ("Team", "$49", ["Team seats", "SLA", "Export & integrations"])
    ]
    html_plans = []
    for name, price, feats in plans:
        lis = "".join(f"<li>{f}</li>" for f in feats)
        html_plans.append(f"""
          <div class="plan">
            <h3>{name}</h3>
            <div class="price">{price}/mo</div>
            <ul>{lis}</ul>
            <button class="btn">Choose {name}</button>
          </div>""")
    return f'<section id="pricing" class="section pricing"><h2>Pricing</h2><div class="grid-3">{"".join(html_plans)}</div></section>'

def contact_section() -> str:
    return """
    <section id="contact" class="section">
      <h2>Contact</h2>
      <form onsubmit="event.preventDefault();alert('Thanks! We will reach you soon.')">
        <div class="row">
          <div><input placeholder="Your name"></div>
          <div><input placeholder="Email address" type="email" required></div>
        </div>
        <div style="margin-top:10px"><textarea rows="5" placeholder="How can we help?"></textarea></div>
        <div style="margin-top:10px"><button class="btn">Send Message</button></div>
      </form>
    </section>"""

def footer_section(title: str) -> str:
    year = datetime.now().year
    return f'<footer class="section"><div class="section" style="padding:0"><span class="muted">© {year} {title}. All rights reserved.</span></div></footer>'

# ---------- Assemble page ----------
def build_preview_html(title: str, description: str, css: str, parts: List[str]) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>{title or "Generated Page"}</title>
  <meta name="description" content="{(description or 'AI generated page with HTML Quick‑Styler')[:180]}">
  <meta property="og:title" content="{title or 'Generated Page'}">
  <meta property="og:description" content="{(description or 'AI generated page with HTML Quick‑Styler')[:180]}">
  <style>{css}</style>
</head>
<body>
  {''.join(parts)}
</body>
</html>"""

def build_index_html_external_css(title: str, description: str, parts: List[str]) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>{title or "Generated Page"}</title>
  <meta name="description" content="{(description or 'AI generated page with HTML Quick‑Styler')[:180]}">
  <meta property="og:title" content="{title or 'Generated Page'}">
  <meta property="og:description" content="{(description or 'AI generated page with HTML Quick‑Styler')[:180]}">
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  {''.join(parts)}
</body>
</html>"""

def save_files_and_zip(index_html: str, css: str) -> Tuple[str, str, str]:
    tmpd = tempfile.mkdtemp(prefix="quick_styler_")
    index_path = os.path.join(tmpd, "index.html")
    css_path = os.path.join(tmpd, "styles.css")
    with open(index_path, "w", encoding="utf-8") as f: f.write(index_html)
    with open(css_path, "w", encoding="utf-8") as f: f.write(css)
    zip_path = os.path.join(tmpd, "site.zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        z.write(index_path, "index.html")
        z.write(css_path, "styles.css")
    return index_path, css_path, zip_path

def build_page(title: str, description: str, palette_key: str, use_llm: bool, hf_token: Optional[str]):
    palettes = ColorPaletteGenerator()
    pal = palettes.get(palette_key)
    css = generate_css(pal)

    gh = GraniteHelper(hf_token if use_llm else None)
    h1, tag = gh.hero(title)
    feats = gh.bullets(title or "this product", n=3)
    about_text = gh.short_para("About this page: " + (title or "project"), 40)

    sections = detect_sections(description)
    parts = [
        f'<header class="sticky"><div class="nav"><div class="brand">{title or "Quick‑Styler"}</div><a class="cta" href="#contact">Contact</a></div></header>',
    ]
    if "hero" in sections: parts.append(hero_section(h1, tag))
    if "features" in sections: parts.append(features_section(feats))
    if "about" in sections: parts.append(about_section(about_text))
    if "portfolio" in sections: parts.append(portfolio_section())
    if "testimonials" in sections: parts.append(testimonials_section())
    if "pricing" in sections: parts.append(pricing_section())
    if "contact" in sections: parts.append(contact_section())
    if "footer" in sections: parts.append(footer_section(title or "Quick‑Styler"))

    html_preview = build_preview_html(title, description, css, parts)
    html_index   = build_index_html_external_css(title, description, parts)
    return html_preview, html_index, css, sections

# ---------- UI ----------
DEFAULT_TITLE = "Modern Portfolio Website"
DEFAULT_DESC = ("Hero section with welcome message, features list with 3 items, about section, "
                "portfolio gallery, testimonials, pricing, contact form, and footer. "
                "Include responsive design & smooth animations.")

palettes = ColorPaletteGenerator()
palette_html = palettes.palette_cards_html()

TEMPLATES_MD = """
### Section Templates
**Hero**: headline, subheadline, two CTAs
**Features**: 3-card grid with icon, title, body
**About**: single card paragraph
**Portfolio**: responsive gallery
**Testimonials**: 3-quote grid
**Pricing**: 3-plan cards (starter, pro, team)
**Contact**: validated form
**Footer**: muted copyright
"""

GUIDE_MD = """
# Guide
1) Fill Title + Description (include section keywords).
2) Pick a color palette.
3) (Optional) Toggle IBM Granite and paste your HF token.
4) Click **Generate Page** → preview + downloads.
"""

with gr.Blocks(title="HTML Quick‑Styler — AI‑Powered HTML/CSS Generator") as demo:
    gr.Markdown("## HTML Quick‑Styler\nCreate a responsive HTML page from a plain description. "
                "Optionally use **IBM Granite 3.3‑2B Instruct** (HF Inference API) for copy suggestions.")
    with gr.Tabs():
        with gr.Tab("Generate Page"):
            with gr.Row():
                with gr.Column(scale=2):
                    title_in = gr.Textbox(label="Page Title", value=DEFAULT_TITLE)
                    desc_in = gr.Textbox(label="Description (mention sections & preferences)", value=DEFAULT_DESC, lines=6)
                    palette_in = gr.Dropdown(choices=palettes.names(), value="modern", label="Color Palette")

                    with gr.Accordion("🔧 AI Options (Optional: IBM Granite via HF Inference)", open=False):
                        use_llm = gr.Checkbox(value=False, label="Use IBM Granite 3.3‑2B for copy")
                        hf_token = gr.Textbox(label="Hugging Face Access Token (write)", type="password")
                        model_id = gr.Textbox(label="Model ID", value="ibm-granite/granite-3.3-2b-instruct")

                    generate_btn = gr.Button("🚀 Generate Page", variant="primary")

                with gr.Column(scale=3):
                    html_out = gr.HTML(label="Live Preview")
                    sections_json = gr.JSON(label="Detected Sections")
                    with gr.Row():
                        dl_html = gr.File(label="index.html")
                        dl_css = gr.File(label="styles.css")
                        dl_zip = gr.File(label="site.zip")

        with gr.Tab("Live Preview"):
            preview_html = gr.HTML(label="Full HTML Preview")

        with gr.Tab("Color Palettes"):
            gr.Markdown("### Built‑in Palettes (8)")
            pal_view = gr.HTML(value=palette_html)

        with gr.Tab("Templates"):
            gr.Markdown(TEMPLATES_MD)

        with gr.Tab("Guide"):
            gr.Markdown(GUIDE_MD)

    def do_generate(title, desc, pal_key, use_ai, token, model_override):
        try:
            # allow overriding Granite model id
            html_preview, html_index, css, sections = build_page(
                title, desc, pal_key, use_ai, token if use_ai else None
            )
            idx_path, css_path, zip_path = save_files_and_zip(html_index, css)

            return (
                html_preview,
                sections,
                gr.update(value=idx_path),
                gr.update(value=css_path),
                gr.update(value=zip_path),
                html_preview
            )
        except Exception as e:
            # show friendly message instead of generic "Error" bubbles
            msg = f"<pre style='color:#f88'>Generation failed: {e}</pre>"
            print("Generation failed:", e)
            return (gr.update(value=msg), [], None, None, None, gr.update(value=msg))

    generate_btn.click(
        fn=do_generate,
        inputs=[title_in, desc_in, palette_in, use_llm, hf_token, model_id],
        outputs=[html_out, sections_json, dl_html, dl_css, dl_zip, preview_html]
    )

demo.launch(share=True)